### PR TITLE
merge for updated mysql connector

### PR DESCRIPTION
**Pull request by laythslewa**

### CODE REVIEW

**Comment by herlesupreeth** [comment]
Thanks for taking effort to contribute. Can you please let me know whether you have tested the IMS registration/Calling to verify that this doesn't break anything?

**Comment by laythslewa** [comment]
Hi supreeth, yes I have tested it, it works fine with kamailio.
this fixes the problem with Mysql 8.x. it shouldn't effect anything if you're using mariadb

**Comment by herlesupreeth** [comment]
Will merge this as soon as I am able to test this PR on my local setup. Thank you once again

**Comment by herlesupreeth** [comment]
Thank you for the contribution

**Pull request merged**
